# Generated by Django 3.2.16 on 2023-08-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
