# Generated by Django 3.2.16 on 2023-08-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_salarytransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='profile_picture',
            field=models.ImageField(default='default_farm.jpg', upload_to='farms_pics/'),
        ),
    ]
