# Generated by Django 3.2.16 on 2023-08-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_farm_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='profile_picture',
            field=models.ImageField(default='DairyFarm01.jpg', upload_to='farms_pics/'),
        ),
    ]
