# Generated by Django 3.2.16 on 2023-08-29 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_farm_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='profile_picture',
            field=models.ImageField(default='media/farms_pics/DairyFarm01.jpg', upload_to='farms_pics/'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_pics/')),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Labour', 'Labour')], default='Labour', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
