# Generated by Django 3.2.16 on 2023-08-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230831_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('read_only', 'Read Only'), ('labour', 'Labour')], default='read_only', max_length=10),
        ),
    ]
