# Generated by Django 3.2.16 on 2023-05-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_salarytransaction'),
        ('farm_finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='salary_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.salarytransaction'),
        ),
    ]
