# Generated by Django 3.2.16 on 2023-04-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_finances', '0002_auto_20230411_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='income',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
