# Generated by Django 3.2.16 on 2023-04-13 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_farm', '0010_auto_20230412_1046'),
        ('farm_finances', '0004_income_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dairy_farm.farm'),
            preserve_default=False,
        ),
    ]
