# Generated by Django 3.2.16 on 2023-05-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0004_animalweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='animal',
            field=models.ForeignKey(limit_choices_to={'sex': 'female'}, on_delete=django.db.models.deletion.CASCADE, to='dairy.animal'),
        ),
    ]
