# Generated by Django 3.2.16 on 2023-05-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0005_alter_milkrecord_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='first_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='second_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='third_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
