# Generated by Django 3.2.16 on 2023-05-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0007_family'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
    ]
