# Generated by Django 3.2.16 on 2023-05-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0010_animal_image_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image_crop',
        ),
        migrations.RemoveField(
            model_name='animalcategory',
            name='image_crop',
        ),
    ]
