# Generated by Django 3.2.16 on 2023-06-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0014_auto_20230608_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeding',
            name='attempt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breeding',
            name='lactation_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
