# Generated by Django 3.2.16 on 2023-06-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0015_auto_20230608_0811'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('farm', 'tag'), name='unique_farm_tag'),
        ),
    ]
