# Generated by Django 3.2.16 on 2023-06-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0016_animal_unique_farm_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
