# Generated by Django 3.2.16 on 2023-08-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0017_alter_animal_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('breeder', 'Breeder'), ('pregnant', 'Pregnant'), ('dry', 'Dry'), ('milking', 'Milking'), ('preg_milking', 'Pre-Milk'), ('calf', 'Calf'), ('other', 'Other')], default='other', max_length=200),
        ),
        migrations.AlterField(
            model_name='breeding',
            name='method',
            field=models.CharField(choices=[('NATURAL', 'Natural'), ('AI', 'Artificial Insemination')], max_length=200),
        ),
    ]
