# Generated by Django 3.2.16 on 2023-09-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_role'),
        ('dairy', '0019_auto_20230903_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalcategory',
            name='is_site_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animalcategory',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_categories', to='accounts.farm'),
        ),
    ]
