# Generated by Django 3.2.16 on 2023-09-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0021_customer_milksale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_number',
            new_name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
