# Generated by Django 3.2.16 on 2023-09-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0025_auto_20230905_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milksale',
            name='price_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
