# Generated by Django 3.2.16 on 2023-09-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0027_milkpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkpayment',
            name='remaining_payment',
        ),
        migrations.RemoveField(
            model_name='milkpayment',
            name='total_milk_payment',
        ),
    ]
