# Generated by Django 3.2.16 on 2023-09-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0029_milkpayment_total_milk_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkpayment',
            name='remaining_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='milkpayment',
            name='total_milk_payment',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
