# Generated by Django 3.2.16 on 2023-10-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0030_auto_20230913_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkpayment',
            name='received_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='milkpayment',
            name='remaining_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='milkpayment',
            name='total_milk_payment',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
    ]
