# Generated by Django 3.2.16 on 2023-03-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_farm', '0002_auto_20230326_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalcategory',
            old_name='name',
            new_name='title',
        ),
    ]
