# Generated by Django 3.2.16 on 2023-04-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_farm', '0004_auto_20230408_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalcategory',
            name='category_icon',
        ),
    ]
