# Generated by Django 3.2.16 on 2023-04-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_farm', '0005_remove_animalcategory_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age',
        ),
        migrations.AddField(
            model_name='animal',
            name='genetics',
            field=models.ManyToManyField(blank=True, to='dairy_farm.Genetics'),
        ),
    ]
