# Generated by Django 3.2.16 on 2023-04-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_farm', '0006_auto_20230409_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='genetics',
        ),
        migrations.RemoveField(
            model_name='genetics',
            name='user',
        ),
    ]
