# Generated by Django 3.2.16 on 2023-04-13 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_farm', '0010_auto_20230412_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='father',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'Male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_father', to='dairy_farm.animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='mother',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'Female'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_mother', to='dairy_farm.animal'),
        ),
    ]
