# Generated by Django 3.2.16 on 2023-04-13 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_farm', '0011_auto_20230413_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('child', 'Child')], max_length=50)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='dairy_farm.animal')),
                ('related_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_animals', to='dairy_farm.animal')),
            ],
        ),
    ]
