# Generated by Django 3.2.16 on 2023-04-15 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_farm', '0012_animalrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy_farm.animal')),
            ],
        ),
    ]
